// File generated by FlutterFire CLI (DUMMY VERSION FOR GIT)
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('FirebaseOptions are not configured for Linux.');
      default:
        throw UnsupportedError(
          'FirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ---------------- WEB ----------------
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'DUMMY_WEB_API_KEY',
    appId: '1:123456789000:web:aaaaaaaaaaaaaaaaaaaaaa',
    messagingSenderId: '123456789000',
    projectId: 'teryaq-demo-project',
    authDomain: 'teryaq-demo.firebaseapp.com',
    storageBucket: 'teryaq-demo.appspot.com',
    measurementId: 'G-AAAAAAAAAA',
  );

  // ---------------- ANDROID ----------------
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'DUMMY_ANDROID_API_KEY',
    appId: '1:123456789000:android:bbbbbbbbbbbbbbbbbbbbbb',
    messagingSenderId: '123456789000',
    projectId: 'teryaq-demo-project',
    storageBucket: 'teryaq-demo.appspot.com',
  );

  // ---------------- IOS ----------------
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'DUMMY_IOS_API_KEY',
    appId: '1:123456789000:ios:cccccccccccccccccccccc',
    messagingSenderId: '123456789000',
    projectId: 'teryaq-demo-project',
    storageBucket: 'teryaq-demo.appspot.com',
    iosBundleId: 'com.example.teryagapp',
  );

  // ---------------- MACOS ----------------
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'DUMMY_MACOS_API_KEY',
    appId: '1:123456789000:macos:dddddddddddddddddddddd',
    messagingSenderId: '123456789000',
    projectId: 'teryaq-demo-project',
    storageBucket: 'teryaq-demo.appspot.com',
    iosBundleId: 'com.example.teryagapp',
  );

  // ---------------- WINDOWS ----------------
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'DUMMY_WINDOWS_API_KEY',
    appId: '1:123456789000:web:eeeeeeeeeeeeeeeeeeeeee',
    messagingSenderId: '123456789000',
    projectId: 'teryaq-demo-project',
    authDomain: 'teryaq-demo.firebaseapp.com',
    storageBucket: 'teryaq-demo.appspot.com',
    measurementId: 'G-BBBBBBBBBB',
  );
}
