FROM python:3.11-slim

# system deps
RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY dummydatagen.py .

CMD ["python", "dummydatagen.py"]
